### ISSUE TITLE
Breeje - Multiplication after Division can cause larger Precision loss

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-bond-judging#49]
Breeje

medium

# Multiplication after Division can cause larger Precision loss

## Summary

There are multiple instances in the code where multiplication is done on the result of division.

## Vulnerability Detail

In several critical calculations like calculating the payouts or current market price, multiplication is done on the result of division which can lead to larger precision loss.

Instances:
1. `payoutFor` method in `BondBaseOSDA.sol`: 

```solidity
File: BondBaseOSDA.sol

548:    uint256 fee = amount_.mulDiv(_teller.getFee(referrer_), 1e5);
549:    uint256 payout = (amount_ - fee).mulDiv(terms[id_].scale, marketPrice(id_));

```
[Link to Code](https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseOSDA.sol#L548-L549)

2. `_currentMarketPrice` method in `BondBaseOSDA.sol`: 

```solidity
File: BondBaseOSDA.sol

Instance 1:

431:    uint256 price = term.oracle.currentPrice(id_).mulDivUp(
440:    price = price * term.oracleConversion;

Instance 2:

451:    uint256 expectedCapacity = initialCapacity.mulDiv(timeRemaining, uint256(term.length));
472:    (term.decaySpeed * (expectedCapacity - market.capacity)) /
477:    uint256 factor = (term.decaySpeed * (market.capacity - expectedCapacity)) /
482:    return price.mulDivUp(adjustment, ONE_HUNDRED_PERCENT);

```
[Link to Code](https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseOSDA.sol)

3. `maxAmountAccepted` method in `BondBaseOFDA`:

```solidity
File: BondBaseOFDA.sol

512:    uint256 quoteCapacity = market.capacityInQuote
513:        ? market.capacity
514:        : market.capacity.mulDiv(price, term.scale);
515:    uint256 maxQuote = market.maxPayout.mulDiv(price, term.scale);
516:    uint256 amountAccepted = quoteCapacity < maxQuote ? quoteCapacity : maxQuote;

523:    uint256 estimatedFee = amountAccepted.mulDiv(

```
[Link to Code](https://github.com/sherlock-audit/2023-02-bond/blob/main/bonds/src/bases/BondBaseOFDA.sol)

## Impact

Larger Precision Loss.

## Code Snippet

Given above.

## Tool used

Manual Review

## Recommendation

Multiply all the numerators first and then divide it with the product of all the denominator to get the least possible precision loss.

**Comment by UsmannK** [comment]
Escalate for 10 USDC

The watson does not show any impact or measurements of the supposed precision loss. The sponsor says that they think the issue is mitigated and provides reasoning. They say "I don't see how the precision can be improved".

No impact is shown in the report or observed by the sponsor. Report lacks POC and does not show any particular negative effects of the arithmetic. This issue should not be a medium according to the Sherlock guidance. The guidance for "Medium" states: 

> Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost. 

No such scenario has been shown.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> The watson does not show any impact or measurements of the supposed precision loss. The sponsor says that they think the issue is mitigated and provides reasoning. They say "I don't see how the precision can be improved".
> 
> No impact is shown in the report or observed by the sponsor. Report lacks POC and does not show any particular negative effects of the arithmetic. This issue should not be a medium according to the Sherlock guidance. The guidance for "Medium" states: 
> 
> > Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost. 
> 
> No such scenario has been shown.
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Breeje16** [comment]
Escalate for 10 USDC

The impact is legit given the sponsors confirmed the finding and are going to Fix it. Especially in the second case, the Precision loss could have been avoided but it was not done.

The impact is quite understood in these cases. It's different in different cases. In the second case, `_currentMarketPrice` is going to return the value of `price` lower than what it should return because of precision loss. As `price` is a critical parameter, it impacts every methods which uses this `price` in the `BondBaseOSDA.sol` e.g: User can get more payout tokens in `purchaseBond` because of lesser `price` value than actual.

```solidity
File: BondBaseOSDA.sol

378:    payout = amount_.mulDiv(term.scale, price); // @audit 'price' value contains precision loss.

```

Given that the precision loss issue is legit here which requires a fix and it has critical usage, it should be considered a valid medium finding which even sponsors confirmed. They are going to fix it too.

Even in the past, such findings have been rewarded as medium: [Link](https://github.com/code-423n4/2023-01-numoen-findings/issues/249)

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> The impact is legit given the sponsors confirmed the finding and are going to Fix it. Especially in the second case, the Precision loss could have been avoided but it was not done.
> 
> The impact is quite understood in these cases. It's different in different cases. In the second case, `_currentMarketPrice` is going to return the value of `price` lower than what it should return because of precision loss. As `price` is a critical parameter, it impacts every methods which uses this `price` in the `BondBaseOSDA.sol` e.g: User can get more payout tokens in `purchaseBond` because of lesser `price` value than actual.
> 
> ```solidity
> File: BondBaseOSDA.sol
> 
> 378:    payout = amount_.mulDiv(term.scale, price); // @audit 'price' value contains precision loss.
> 
> ```
> 
> Given that the precision loss issue is legit here which requires a fix and it has critical usage, it should be considered a valid medium finding which even sponsors confirmed. They are going to fix it too.
> 
> Even in the past, such findings have been rewarded as medium: [Link](https://github.com/code-423n4/2023-01-numoen-findings/issues/249)

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Oighty** [comment]
Issue fixed here: https://github.com/Bond-Protocol/bonds/pull/50

**Comment by xiaoming9090** [comment]
Fixed in https://github.com/Bond-Protocol/bonds/pull/50

**Comment by hrishibhat** [comment]
Escalation accepted

Given that there are no details/calculations presented on the loss this issue could potentially cause, considering this issue a low severity.

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Given that there are no details/calculations presented on the loss this issue could potentially cause, considering this issue a low severity. 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
